version: '3'
services:

  sales-db:
    image: mongo
    container_name: sales-db
    restart: always
    networks:
      - sales-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
      - MONGO_INITDB_DATABASE=sales_db
    ports:
      - 27017:27017

  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  sales-rabbit:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    hostname: sales-rabbit
    networks:
      - sales-network
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672

  product-db:
    image: postgres
    container_name: product-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

  product-api:
    build: './product-api'
    container_name: product-api
    depends_on:
      - product-db
      - sales-rabbit
    networks:
      - sales-network
    environment:
      - PORT=8081
      - SECRET_KEY=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY3OA==
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_NAME=product_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RABBITMQ_HOST=sales-rabbit
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    depends_on:
      - sales-db
      - sales-rabbit
    networks:
      - sales-network
    environment:
      - PORT=8082
      - SECRET_KEY=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY3OA==
      - MONGO_URL=mongodb://mongoadmin:mongoadmin@sales-db:27017/sales_db?authSource=admin
      - RABBIT_URL=amqp://sales-rabbit:5672
      - PRODUCT_API_URL=http://product-api:8081/api
      - NODE_ENV=container
    ports:
      - 8082:8082

  auth-api:
    build: './auth-api'
    container_name: auth-api
    depends_on:
      - auth-db
    networks:
      - sales-network
    environment:
      - PORT=8080
      - SECRET_KEY=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY3OA==
      - DATABASE_NAME=auth_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=auth-db
      - DATABASE_PORT=5432
      - NODE_ENV=container
    ports:
      - 8080:8080

networks:
  sales-network:
    driver: bridge
