server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql   
    
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  main:
    allow-circular-references: true       
