server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql   
    
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  
  main:
    allow-circular-references: true    
    allow-bean-definition-overriding: true   

app-config:
  services:
    sales: http://${SALES_HOST:localhost}:${SALES_PORT:8082} 
  
  secrets:
    SECRET_KEY: ${SECRET_KEY:YXV0aC1hcGktc2VjcmV0LWtleS0xMjM0NTY3ODkxMA==}
    
  rabbit:
    exchange:
      product: product.topic     
    routingKey:
      product-stock: product-stock-update.routingKey
      sales-confirmation: sales-confirmation.routingKey
    queue:
      product-stock: product-stock-update.queue
      sales-confirmation: sales-confirmation.queue
    